### PR TITLE
Add neotree faces

### PR DESCRIPTION
**Pull request by geekerzp**

### CODE REVIEW

**Comment by geekerzp** [comment]
@arcticicestudio

**Comment by arcticicestudio** [comment]
Thanks for your contribution 👍 
I've adjusted some colors of the faces to match the Nord UI style and added the missing NeoTree faces.
I'll merge it into the next package release version. It will be availabe from MELPA as soon as the next build runs.

**Comment by arcticicestudio** [comment]
<p align="center"><strong>Preview</strong><br></p>

**Comment by arcticicestudio** [comment]
🚢 Shipped with MELPA package release version 🏷 [0.5.0](https://github.com/arcticicestudio/nord-emacs/releases/tag/v0.5.0).

**Comment by geekerzp** [comment]
Cool!

**Pull request merged**
