### PR TITLE
Please normalize the license file

### PR DESCRIPTION
**Pull request by tarsius**
Rename it from LICENSE.md to LICENSE and remove the markdown.
Also add a License header keyword to nord-emacs.el.

This helps tools that try to automatically detect the license
(such as those used by Github and the Emacsmirror) to do their
job.

Thanks for considering this.

### CODE REVIEW

**Comment by tarsius** [comment]
Friendly ping!

**Comment by arcticicestudio** [comment]
Sorry for the delay, haven't got free time to work on my projects.

Is there a specific reason why the Emacsmirror algorithm is not able to detect files with a `.md` extension?
I've chosen the Markdown format for all of my projects license files due to the better readability, the [GitHub documentation recommendations](https://help.github.com/articles/adding-a-license-to-a-repository) and the fact that it seems like a GitHub standard. GitHub also creates a `.md` license when using the templates for new repositories and [detects the license type](https://github.com/atom/atom/blob/master/LICENSE.md).

gh-40-scrot-atom-license

Anyway, the documentation also says the file can be named `LICENSE` and if it is a kind of standard for Emacs projects there's absolute no problem to change by merging your changes, just wanted to know the background behind it.

**Comment by tarsius** [comment]
> Is there a specific reason why the Emacsmirror algorithm is not able to detect files with a .md extension?

Actually that would work too, but something appears to go wrong. I suspect that your copy of the license is too different from the vanilla version in some way for `licensee` to still recognize it (at least with the default settings).

I extract license information from a package's "main library" using my own (rather crappy) code. But if that fails I also use `licensee` to get that information from the license file. Github uses that same tool.

The easiest fix as I am concerned (and I have to deal with a hundreds such issues), would be to just add this line to the library header:

```lisp
;;; License: Apache-2.0
```

Thanks!

**Comment by arcticicestudio** [comment]
Thanks for your explanation :+1: 

I'll go ahead and add the line to the theme if the changes to the `LICENSE.md` file are not necessarily necessary and are sufficient to properly recognize the license type.

Would be nice if you'd let me know if it works afterwards.

**Comment by arcticicestudio** [comment]
I've created #41 and merged #42. 

> Would be nice if you'd let me know if it works afterwards.

**Comment by arcticicestudio** [comment]
Superseded by #41

**Comment by tarsius** [comment]
Thanks!
It works.

When will this change be merged into `master`?

**Comment by tarsius** [comment]
Actually, I think I should just mirror `develop` instead of `master`.

**Comment by arcticicestudio** [comment]
The project uses the gitflow branching model, so the `master` branch contains the annotated version tags while `develop` contains the latest commits.

I've got a free day today, actually working on some port projects and hope to implement a feature (theme config) today, so maybe there will be a new release today in `master`.

**Pull request closed without merging**
